name: Deploy Dashboard to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - dashboard/frontend/**
      - .github/workflows/deploy-pages.yml
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@39370e3973a6a06d9939e118128b6d26c6360c3d # v4.1.0
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'dashboard/frontend/package-lock.json'

      - name: Install Dependencies
        run: npm ci
        working-directory: dashboard/frontend

      - name: Build Application
        run: npm run build
        working-directory: dashboard/frontend

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@65b5d2fb95409e0cad75dcc18af3d06e2510edd9 # v4.6.1
        with:
          folder: dashboard/frontend/dist
          branch: gh-pages
